name = "DesignDriveCoilFilt"
uuid = "7f9b101c-f22f-4d17-9683-ff0620ab1ca2"
authors = ["Eli Mattingly"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
